# -*- coding: utf-8 -*-
"""LightGBM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBN_LZ2_wANsRIOfsNhJCA-MiO_St-Fv
"""

import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from lightgbm import LGBMClassifier
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, roc_auc_score, classification_report
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import joblib

def main():

    print("Loading datasets...")

    df_train = pd.read_csv('processed_data/train_dataset.csv')

    feature_cols = [
        'max_amp',
        'mean_mag',
        'var_mag',
        'spectral_energy',
        'spectral_centroid',
        'spectral_spread',
        'peak_f1',
        'peak_f2',
        'peak_f3'
    ]

    # -------------------------------------------------------------
    # Unsupervised Fault Assignment (K-Means)
    # -------------------------------------------------------------

    faulty_mask = df_train['label'] == 1

    X_faulty = df_train.loc[faulty_mask, feature_cols]

    scaler = StandardScaler()

    X_faulty_scaled = scaler.fit_transform(X_faulty)

    kmeans = KMeans(
        n_clusters=3,
        random_state=42,
        n_init=10
    )

    clusters = kmeans.fit_predict(X_faulty_scaled)

    # 1: Inner Race
    # 2: Outer Race
    # 3: Combination

    cluster_mapping = {

        pd.Series(clusters).value_counts().index[0]: 1,
        pd.Series(clusters).value_counts().index[1]: 2,
        pd.Series(clusters).value_counts().index[2]: 3
    }

    # Replace faulty class with subclass labels

    df_train.loc[faulty_mask, 'label'] = [
        cluster_mapping[c] for c in clusters
    ]

    # -------------------------------------------------------------
    # PCA Visualization
    # -------------------------------------------------------------

    pca = PCA(n_components=2)

    X_pca = pca.fit_transform(X_faulty_scaled)

    mapped_clusters = [cluster_mapping[c] for c in clusters]

    plt.figure(figsize=(8, 6))

    label_names = {
        1: 'Inner Race Defect',
        2: 'Outer Race Defect',
        3: 'Combination Defect'
    }

    str_labels = [label_names[l] for l in mapped_clusters]

    sns.scatterplot(
        x=X_pca[:, 0],
        y=X_pca[:, 1],
        hue=str_labels,
        palette='viridis',
        s=100
    )

    plt.title('Fault Sub-Classes Segmented via K-Means (PCA) - LightGBM Run')

    plt.xlabel('Principal Component 1')

    plt.ylabel('Principal Component 2')

    plt.legend(title='Defect Variant')

    plt.tight_layout()

    plt.savefig('processed_data/fault_clusters_multiclass_lgbm.png')

    plt.close()

    # -------------------------------------------------------------
    # Cross Validation + SMOTE
    # -------------------------------------------------------------

    X = df_train[feature_cols]

    y = df_train['label']

    print(f"\nFinal Training Class Distribution:\n{y.value_counts()}")

    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    lgbm_model = LGBMClassifier(

        n_estimators=100,
        random_state=42,
        class_weight='balanced',
        num_leaves=15,
        min_child_samples=5,
        verbose=-1
    )

    lgbm_pipeline = ImbPipeline([

        ('smote', SMOTE(random_state=42, k_neighbors=1)),
        ('lgbm', lgbm_model)
    ])

    scoring = [
        'accuracy',
        'precision_macro',
        'recall_macro',
        'f1_macro'
    ]

    cv_results = cross_validate(

        lgbm_pipeline,
        X,
        y,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    print("\n--- 5-Fold Stratified Cross Validation (LightGBM + SMOTE) ---")

    print(f"Mean CV Accuracy:  {np.mean(cv_results['test_accuracy']):.4f}")

    print(f"Mean CV Precision: {np.mean(cv_results['test_precision_macro']):.4f}")

    print(f"Mean CV Recall:    {np.mean(cv_results['test_recall_macro']):.4f}")

    print(f"Mean CV F1-Score:  {np.mean(cv_results['test_f1_macro']):.4f}")

    # -------------------------------------------------------------
    # Final Training
    # -------------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(

        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    smote = SMOTE(
        random_state=42,
        k_neighbors=1
    )

    X_train_res, y_train_res = smote.fit_resample(
        X_train,
        y_train
    )

    final_lgbm = LGBMClassifier(

        n_estimators=100,
        random_state=42,
        class_weight='balanced',
        num_leaves=15,
        min_child_samples=5,
        verbose=-1
    )

    final_lgbm.fit(
        X_train_res,
        y_train_res
    )

    # -------------------------------------------------------------
    # Evaluation
    # -------------------------------------------------------------

    test_preds = final_lgbm.predict(X_test)

    test_probs = final_lgbm.predict_proba(X_test)

    roc_auc = roc_auc_score(
        y_test,
        test_probs,
        multi_class='ovr'
    )

    print(f"\nModel ROC-AUC Score (OVR): {roc_auc:.4f}")

    print("\nClassification Report:\n")

    print(classification_report(
        y_test,
        test_preds
    ))

    # -------------------------------------------------------------
    # Confusion Matrix
    # -------------------------------------------------------------

    cm = confusion_matrix(
        y_test,
        test_preds
    )

    actual_label_names = [
        'Healthy',
        'Inner Race',
        'Outer Race',
        'Combination'
    ]

    plt.figure(figsize=(8, 6))

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Greens',
        xticklabels=actual_label_names,
        yticklabels=actual_label_names
    )

    plt.ylabel('Actual Classification')

    plt.xlabel('Predicted Classification')

    plt.title('Multi-Class LightGBM Confusion Matrix')

    plt.tight_layout()

    plt.savefig('processed_data/multiclass_lgbm_cm.png')

    plt.close()

    # -------------------------------------------------------------
    # Feature Importance
    # -------------------------------------------------------------

    importances = final_lgbm.feature_importances_

    plt.figure(figsize=(8, 5))

    sns.barplot(
        x=importances,
        y=feature_cols
    )

    plt.title('LightGBM Feature Importances')

    plt.xlabel('Importance Score')

    plt.tight_layout()

    plt.savefig('processed_data/lgbm_feature_importances.png')

    plt.close()

    # -------------------------------------------------------------
    # Save Model
    # -------------------------------------------------------------

    joblib.dump(
        final_lgbm,
        'processed_data/final_lgbm_model.pkl'
    )

    print("\nSaved LightGBM model to processed_data/final_lgbm_model.pkl")


if __name__ == "__main__":
    main()